### ISSUE TITLE
Last meetup's examples

### ISSUE THREAD

**Issue by ehernandez-xk** [dockerguatemala/meetups#2]
Last meetup we saw some examples about Multi Stage Builds, would be great to have them here.

https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by chentex** [comment]
That would be great to have. Let's see if @christianhxc has time to add them.

**Comment by chrismld** [comment]
@ehernandez-xk @chentex PR it's on its way :) ... you can also use my personal repo: https://github.com/christianhxc/docker-multi-stage-101

Feel free to improve them, make suggestions or even ask questions, I'm happy to help
